# Form implementation generated from reading ui file '.\barrier.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(827, 539)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        widget.setWindowIcon(icon)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 821, 531))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImageLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageLabel.sizePolicy().hasHeightForWidth())
        self.ImageLabel.setSizePolicy(sizePolicy)
        self.ImageLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.ImageLabel.setMaximumSize(QtCore.QSize(640, 480))
        self.ImageLabel.setObjectName("ImageLabel")
        self.horizontalLayout.addWidget(self.ImageLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 40, 10, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.ArrorTool = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.ArrorTool.setObjectName("ArrorTool")
        self.verticalLayout_3.addWidget(self.ArrorTool)
        self.PencelTool = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.PencelTool.setObjectName("PencelTool")
        self.verticalLayout_3.addWidget(self.PencelTool)
        self.EraserTool = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.EraserTool.setObjectName("EraserTool")
        self.verticalLayout_3.addWidget(self.EraserTool)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.UndoButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.UndoButton.setObjectName("UndoButton")
        self.verticalLayout_2.addWidget(self.UndoButton)
        self.SaveButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_2.addWidget(self.SaveButton)
        self.CancelButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.verticalLayout_2.addWidget(self.CancelButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(widget)
        self.CancelButton.clicked.connect(widget.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(widget)
        widget.setTabOrder(self.ArrorTool, self.PencelTool)
        widget.setTabOrder(self.PencelTool, self.EraserTool)
        widget.setTabOrder(self.EraserTool, self.UndoButton)
        widget.setTabOrder(self.UndoButton, self.SaveButton)
        widget.setTabOrder(self.SaveButton, self.CancelButton)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "屏障设置"))
        self.ImageLabel.setText(_translate("widget", "TextLabel"))
        self.ArrorTool.setText(_translate("widget", "Arror"))
        self.PencelTool.setText(_translate("widget", "Pencel"))
        self.EraserTool.setText(_translate("widget", "Eraser"))
        self.UndoButton.setText(_translate("widget", "Undo"))
        self.SaveButton.setText(_translate("widget", "Save"))
        self.CancelButton.setText(_translate("widget", "Cancel"))
