# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1281, 101))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.TopButtonVLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.TopButtonVLayout.setContentsMargins(0, 0, 0, 0)
        self.TopButtonVLayout.setObjectName("TopButtonVLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TopButtonVLayout.addItem(spacerItem)
        self.SourceButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.SourceButton.setObjectName("SourceButton")
        self.TopButtonVLayout.addWidget(self.SourceButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TopButtonVLayout.addItem(spacerItem1)
        self.thresholdButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.thresholdButton.setObjectName("thresholdButton")
        self.TopButtonVLayout.addWidget(self.thresholdButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TopButtonVLayout.addItem(spacerItem2)
        self.barrierButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.barrierButton.setObjectName("barrierButton")
        self.TopButtonVLayout.addWidget(self.barrierButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TopButtonVLayout.addItem(spacerItem3)
        self.quitButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.quitButton.setObjectName("quitButton")
        self.TopButtonVLayout.addWidget(self.quitButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.TopButtonVLayout.addItem(spacerItem4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 1281, 621))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.InfoHLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.InfoHLayout.setContentsMargins(20, 20, 20, 20)
        self.InfoHLayout.setObjectName("InfoHLayout")
        self.VideoLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.VideoLabel.setText("")
        self.VideoLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.VideoLabel.setObjectName("VideoLabel")
        self.InfoHLayout.addWidget(self.VideoLabel)
        self.ForbidView = QtWidgets.QListView(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ForbidView.sizePolicy().hasHeightForWidth())
        self.ForbidView.setSizePolicy(sizePolicy)
        self.ForbidView.setObjectName("ForbidView")
        self.InfoHLayout.addWidget(self.ForbidView)

        self.retranslateUi(Form)
        self.quitButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.SourceButton, self.thresholdButton)
        Form.setTabOrder(self.thresholdButton, self.barrierButton)
        Form.setTabOrder(self.barrierButton, self.quitButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "基于多尺度特征融合的高速公路违章行驶车辆识别与处理系统"))
        self.SourceButton.setText(_translate("Form", "视频源设置"))
        self.thresholdButton.setText(_translate("Form", "阈值设置"))
        self.barrierButton.setText(_translate("Form", "屏障设置"))
        self.quitButton.setText(_translate("Form", "退出"))
